# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d68f4f703786082ae7779eb669953aba725bf0a622836e7af07659ae4abc85891183f13ea060995dd9f06d0a09f9573aa0512514b2595cf0b2d8580fb3a78ee

test:
  secret_key_base: 87aeeda850fdae03405ba545f4daaaa4b2cd2a0bc486f793a9fe3c022457d6344d88b5200a7669c6e61b0608cfb010294b0fef09db0164f264cd472e88e42710

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
